print(".......................第一题.................................")
import numpy as np
a1=np.array([[1,3,6],[2,4,5],[3,4,7]])
a2=np.array([[12,13,14],[15,16,17],[18,19,20]])
print(a1*a2)
print(a1/a2)
print(a1-a2)
print(a1+a2)
print(".......................第二题.................................")
c=np.arange(10).reshape(5,2)
c=np.mat(c)
print(c)
d=np.arange(10).reshape(2,5)
d=np.mat(d)
print(d)
print(c*d)
print(d*c)
print(".......................第三题.................................")
b=np.random.randint(10,size=(4,4))
print(b)
print(".......................第四题.................................")
import numpy.linalg as nlg
b= np.mat(b)
print("b:")
print(b)
ia=nlg.inv(b)
print("inverse of b:")
print(ia)
print("b*inv(b)")
print(b*ia)
print(".......................第五题.................................")
eig_value,eig_vector=nlg.eig(b)
print("eigen value:")
print(eig_value)
print("eigen vector:")
print(eig_vector)
print(".......................第六题.................................")
from pandas import Series, DataFrame
a3=np.random.randn(10)
df=DataFrame(a3)
print(df)
print("........................第七.题.................................")
d={'one':Series([1.,2.,3.],index=['a','b','c']),'two':Series([1.,2.,3.,4.],index=['a','b','c','d']),
   'three':Series([7.,8.,9.],index=['a','b','c']),'for':Series([10.,11.,12.,13.],index=['a','b','c','d'])}
df=DataFrame(d)
print(df)
print('Selecting by')
print(df[1:3])
print(".......................第九题.................................")
import tushare as ts
dt=ts.get_stock_basics()
print(dt)
print(dt.sort_values('totals',ascending=0).head(20))
print(".......................第十题.................................")
print(dt[dt['industry']=='全国地产'])
print(".......................第十一题.................................")
db=(dt[dt['industry']=='全国地产'])
print(db.sort_values('totals',ascending=0).head(10))
print(".......................第十二题.................................")
dt_grp=dt.groupby('area')
print(dt_grp.count().sort_values('totals',ascending=0).head(10))
